name: unified-pinns
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.11.9
  - pip:
      - argparse==1.4.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - ml-dtypes==0.4.0
      - numpy==2.0.0
      - opt-einsum==3.3.0
      - scipy==1.14.0